# The server section is only required for garo-server
server:
  listenAddress: :8080

# The agent section is only required for garo-agent
agent:
  serverAddress: http://localhost:8080
  refreshInterval: 1s
  repositories:
    - philips-internal/fact-service
    - philips-internal/crocs
    - philips-internal/varys
