// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/garo/service.proto

package garo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GetAgentConfigurationRequest request the configuration for a given repository and organization
type GetAgentConfigurationRequest struct {
	Organisation         string   `protobuf:"bytes,1,opt,name=organisation,proto3" json:"organisation,omitempty"`
	Repository           string   `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAgentConfigurationRequest) Reset()         { *m = GetAgentConfigurationRequest{} }
func (m *GetAgentConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*GetAgentConfigurationRequest) ProtoMessage()    {}
func (*GetAgentConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07eb44b64dbde6c2, []int{0}
}

func (m *GetAgentConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentConfigurationRequest.Unmarshal(m, b)
}
func (m *GetAgentConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentConfigurationRequest.Marshal(b, m, deterministic)
}
func (m *GetAgentConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentConfigurationRequest.Merge(m, src)
}
func (m *GetAgentConfigurationRequest) XXX_Size() int {
	return xxx_messageInfo_GetAgentConfigurationRequest.Size(m)
}
func (m *GetAgentConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentConfigurationRequest proto.InternalMessageInfo

func (m *GetAgentConfigurationRequest) GetOrganisation() string {
	if m != nil {
		return m.Organisation
	}
	return ""
}

func (m *GetAgentConfigurationRequest) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

// AgentConfigurationResponse returns agent configuration options
type AgentConfigurationResponse struct {
	TotalAllowedRunners  int32    `protobuf:"varint,1,opt,name=totalAllowedRunners,proto3" json:"totalAllowedRunners,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentConfigurationResponse) Reset()         { *m = AgentConfigurationResponse{} }
func (m *AgentConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*AgentConfigurationResponse) ProtoMessage()    {}
func (*AgentConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07eb44b64dbde6c2, []int{1}
}

func (m *AgentConfigurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentConfigurationResponse.Unmarshal(m, b)
}
func (m *AgentConfigurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentConfigurationResponse.Marshal(b, m, deterministic)
}
func (m *AgentConfigurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentConfigurationResponse.Merge(m, src)
}
func (m *AgentConfigurationResponse) XXX_Size() int {
	return xxx_messageInfo_AgentConfigurationResponse.Size(m)
}
func (m *AgentConfigurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentConfigurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AgentConfigurationResponse proto.InternalMessageInfo

func (m *AgentConfigurationResponse) GetTotalAllowedRunners() int32 {
	if m != nil {
		return m.TotalAllowedRunners
	}
	return 0
}

func init() {
	proto.RegisterType((*GetAgentConfigurationRequest)(nil), "philips.garo.garo.GetAgentConfigurationRequest")
	proto.RegisterType((*AgentConfigurationResponse)(nil), "philips.garo.garo.AgentConfigurationResponse")
}

func init() { proto.RegisterFile("rpc/garo/service.proto", fileDescriptor_07eb44b64dbde6c2) }

var fileDescriptor_07eb44b64dbde6c2 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4f, 0x03, 0x31,
	0x0c, 0x85, 0x75, 0x08, 0x2a, 0x61, 0xb1, 0x10, 0x04, 0x2a, 0x15, 0x42, 0xe8, 0x26, 0x16, 0x72,
	0x08, 0x7e, 0x41, 0x61, 0x60, 0x63, 0x08, 0x1b, 0x5b, 0x5a, 0x4c, 0x88, 0x14, 0xc5, 0xc1, 0xf6,
	0x51, 0xf1, 0x3f, 0xf8, 0xc1, 0xa8, 0x61, 0x01, 0x35, 0x74, 0xf1, 0xf0, 0xde, 0xb3, 0x9f, 0x3e,
	0xc3, 0x09, 0x97, 0xe5, 0x10, 0x3c, 0xd3, 0x20, 0xc8, 0x1f, 0x71, 0x89, 0xb6, 0x30, 0x29, 0x99,
	0xc3, 0xf2, 0x16, 0x53, 0x2c, 0x62, 0xd7, 0x5e, 0x1d, 0xfd, 0x02, 0xce, 0x1e, 0x50, 0xe7, 0x01,
	0xb3, 0xde, 0x53, 0x7e, 0x8d, 0x61, 0x64, 0xaf, 0x91, 0xb2, 0xc3, 0xf7, 0x11, 0x45, 0x4d, 0x0f,
	0x07, 0xc4, 0xc1, 0xe7, 0x28, 0x55, 0x9e, 0x76, 0x17, 0xdd, 0xe5, 0xbe, 0xfb, 0xa3, 0x99, 0x73,
	0x00, 0xc6, 0x42, 0x12, 0x95, 0xf8, 0x73, 0xba, 0x53, 0x13, 0xbf, 0x94, 0xfe, 0x11, 0x66, 0xad,
	0x02, 0x29, 0x94, 0x05, 0xcd, 0x35, 0x1c, 0x29, 0xa9, 0x4f, 0xf3, 0x94, 0x68, 0x85, 0x2f, 0x6e,
	0xcc, 0x19, 0x59, 0x6a, 0xd1, 0x9e, 0x6b, 0x59, 0x37, 0x5f, 0x1d, 0x9c, 0x6e, 0x1e, 0x7c, 0xfa,
	0x41, 0x35, 0x2b, 0x38, 0x6e, 0x12, 0x99, 0xc1, 0x6e, 0xe0, 0xdb, 0x6d, 0xec, 0xb3, 0xab, 0xc6,
	0xc2, 0xff, 0x20, 0x77, 0x93, 0xe7, 0xdd, 0x75, 0x64, 0x31, 0xa9, 0xcf, 0xbe, 0xfd, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x2b, 0x1b, 0xe2, 0x69, 0x86, 0x01, 0x00, 0x00,
}
