name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Lint
        run: |
          go install golang.org/x/tools/cmd/goimports
          result=$($(go env GOPATH)/bin/goimports -d -e -local github.com/philips-labs .)
          echo $result
          [ -n "$result" ] && exit 1 || exit 0

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v .

      - name: Test and Cover
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: go test -v -race -count=1 -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
