name: CI

on: [push, pull_request]

jobs:
  gomod:
    name: Go Modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13, 1.14]

      fail-fast: false
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Lint
        run: |
          go install golang.org/x/tools/cmd/goimports
          result=$($(go env GOPATH)/bin/goimports -d -e -local github.com/philips-labs .)
          echo $result
          [ -n "$result" ] && exit 1 || exit 0

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: make compile

      - name: Test and Cover
        env:
          GARO_GH_TOKEN: ${{ secrets.GARO_GH_TOKEN }}
        run: make test-cover

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
